version: '3.8'
services:
  corese:
    image: wimmics/corese:latest
    hostname: corese
    environment:
      OPTIONS: "-su"
    expose: 
      - "8080"
    volumes:
      - ./output:/usr/local/corese/log
      - ./config:/usr/local/corese/config
  indegx:
    build: https://github.com/Wimmics/IndeGx.git#FAIRSavoirExperiment
    depends_on:
      - corese
    volumes:
      - ./input:/input
      - ./output:/output
      - ./config:/indegx/config